<?php

namespace Epita\EpitaBundle\Entity;

/**
 * questionanswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class questionanswerRepository extends \Doctrine\ORM\EntityRepository
{
}
