<?php

namespace Epita\EpitaBundle\Entity;

/**
 * resourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class resourceRepository extends \Doctrine\ORM\EntityRepository
{
}
